using System;

namespace Nexon.Com.UserWrapper
{
	public enum ErrorCode
	{
		NoError,
		DBError,
		DataSetCreateError,
		SoapCallError,
		SoapInitError,
		SoapInvalidAccessError,
		XMLParsingError,
		SoapServerError,
		CryptError,
		FailSendEmail,
		ModuleCallError,
		NotSupportError = 99,
		UnKnowError = 98,
		Common_EmptyInputData = 100,
		Common_InvalidInputData,
		Common_FailSendEmail,
		Common_HasWhiteSpace,
		Common_InValidAccess,
		Common_IsModifySameData,
		CheckRealName_CBNameError = 1000,
		CheckRealName_SIRENError,
		CheckRealName_KaitError,
		CheckRealName_WrongNameorWrongSocNo,
		CheckRealName_WrongData,
		CheckRealName_NoData,
		CheckRealName_Fail,
		Auth_NotCompleteAuthStep = 1100,
		Password_InVaildChangeUseType = 1010,
		Password_InVaildChangeMethodType,
		Password_EmptyPwdNew,
		Password_EmptyPwdCfm,
		Password_NoMatchNewnCfm,
		Password_InValidPwd_EqualNexonID,
		Password_InValidPwd_IllegalCharacter,
		Password_InValidPwd_Exist3DuplicateWord,
		Password_InValidPwd_NoMixture,
		Password_NoMatchSsn,
		Password_FailSendEmail_TempPassword,
		Password_MatchPwdOld = 1025,
		MobileAuth_OverMaxCount_Ssn = 1021,
		MobileAuth_OverMaxCount_PhoneNum,
		MobileAuth_OverMaxCount_IP,
		MobileAuth_OverMaxTryFailCount_Ssn,
		MobileAuth_OverMaxTrySuccessCount_Ssn = 1030,
		OwnEmailAuth_OverMaxTryFailCount_Ssn = 1026,
		OwnEmailAuth_OverMaxCount_Ssn,
		OwnEmailAuth_OverMaxCount_Email,
		OwnEmailAuth_OverMaxCount_IP,
		ParentAuth_InVaildAuth = 2000,
		ParentAuth_InVaildAuthMethodCode,
		ParentAuth_RejectCashAuth,
		ParentAuth_OverMaxAuthCountJoinBySsn,
		ParentAuth_OverMaxAuthCountCashBySsn,
		ParentAuth_CompleteJoinAuth,
		ParentAuth_CompleteCashAuth,
		ParentAuth_InvalidBirthDay,
		ParentAuth_NotJoinAuthUnder14,
		ParentAuth_OverMaxAuthCountJoinByEmail,
		ParentInfo_OverByteSize_Name = 2110,
		ParentInfo_OverByteSize_Ssn,
		ParentInfo_OverByteSize_Email,
		ParentInfo_OverByteSize_Phone,
		ParentInfo_OverByteSize_MobilePhone,
		ParentInfo_InvalidSsn,
		ParentInfo_IsNotCorrectAgeDifference,
		Join_NexonIDCheck_EqualNexonName = 3000,
		Join_NexonIDCheck_ReservedID,
		Join_NexonIDCheck_RestrictID,
		Join_NexonIDCheck_DuplicateID,
		Join_NexonNameCheck_EqualNexonID,
		Join_NexonNameCheck_ReservedNexonName,
		Join_NexonNameCheck_RestrictNexonName,
		Join_NexonNameCheck_DuplicateNexonName,
		Join_IsAlreadyOverJoinSsn,
		Join_NotAllowJoinBefore7Day,
		Join_JoinCoolTime,
		Join_BlackListSsn,
		Join_School_DBError,
		Join_BlockedIP,
		Join_InvalidRegisterCode,
		Join_NexonIDCheck_IllegalCharacter,
		User_NotExistUser = 4000,
		User_NotPwdHashMatch,
		User_IsTempUser_Foreigner,
		User_NotOwnerCfm,
		User_BlockByAdmin,
		User_LoginBlockBySafeLogin = 4028,
		User_TempBlockByLoginFail = 4005,
		User_AdultTempUser,
		User_BlockByEvent,
		User_OverByteSize_Name,
		User_OverByteSize_Ssn,
		User_OverByteSize_Email,
		User_OverByteSize_PwdHintAnswer,
		User_OverByteSize_Address,
		User_OverByteSize_Phone,
		User_OverByteSize_MobilePhone,
		User_TempUser_Child,
		User_TempUser_Cash,
		User_BlockCashRefillByAdmin,
		User_CashParentReject,
		User_IsForeigner,
		User_IsIpinUser,
		User_IsNotIpinUser,
		User_UnderByteSize_PwdHintAnswer,
		User_IsDormantID,
		User_IsNotDormantID,
		User_IsStealID,
		User_IsNotStealID,
		User_IsChannelingUser,
		UserInfo_InvalidSsn = 5000,
		UserInfo_NoMatchSsn,
		UserInfo_EmptyEmail,
		UserInfo_InvalidEmail,
		UserInfo_StopEmailServiceDomain,
		UserInfo_EqualParentEmailnChildEmail,
		UserInfo_InvalidBirthDay,
		UserInfo_InvalidBirthDay_Year,
		UserInfo_InvalidSchoolInfo,
		UserInfo_DuplicateSchoolInfo,
		UserInfo_EmptyName,
		UserInfo_InvalidName,
		UserInfo_Exist2DuplicateWordName,
		UserInfo_NotKoreanLastName,
		UserInfo_NotOnlyHangeulName,
		UserInfo_InvalidPhoneNum,
		UserInfo_InvalidMobilePhoneNum,
		UserInfo_InvalidMobileCompanyCode,
		UserInfo_InvalidAddressCode,
		UserInfo_NoMatchUserInfo,
		UserInfo_Age_Under3,
		UserInfo_Age_Over90,
		UserInfo_Age_Under18,
		UserInfo_InvalidPwdHint,
		UserInfo_EmptyPwdHintAnswer,
		UserInfo_InvalidMemoIncomingCode,
		UserInfo_Invalid_IpinNo,
		UserInfo_Invalid_IpinCIInfo,
		UserInfo_Invalid_IpinBirth,
		UserInfo_Invalid_IpinSexCode,
		UserInfo_InvalidPartialssn,
		UserInfo_InvalidIdentitySN,
		UserInfo_Age_0,
		UserInfo_NoMatchName,
		UserInfo_NotExistIdentitySN,
		UserInfo_Invalid_IpinLogSN,
		UserInfo_AlreadyOwnEmail,
		UserInfo_InvalidPwdHintAnswer,
		UserInfo_InvalidBirthCode,
		UserInfo_NoMatchIdentitySN,
		UserInfo_Age_Under14,
		UserInfo_OverMaxCountChangeNexonName,
		UserInfo_Invalid_NexonNameChangeUseCode,
		UserInfo_EqualNexonName,
		Secede_InvaildSecedeType = 6000,
		Secede_IsExistGameID,
		Secede_SecedeAllGuildError,
		Secede_NotOwnerConfirm_BlockedByAdmin,
		Secede_NotOwnerConfirm_BlockedBySafeLogin,
		NED_Invalid_RowAccessorID = 7000,
		NED_Invalid_Argument,
		NED_No_More_Column,
		NED_Initialized_Needed,
		NED_SoapFail = 7100,
		NED_SoapError,
		NED_DecodeFail,
		NED_Access_Denied = 7200,
		NED_Unregistered_Column,
		NED_Invalid_DataBlock,
		NED_NoMatchENCData = 7400,
		NED_UnknownError,
		NED_EncryptColumnError,
		NED_DecryptColumnError,
		NED_UninitializedNEDWrapper,
		Ipin_GetCI = 7500,
		Login_Success_IsAlreadyLoginByAnotherComputer = 8000,
		Login_Fail_AdultTempUser,
		Login_Fail_AuthSystem_WrongIDorPassword,
		Login_Fail_AuthSystem_WithdrawnUser,
		Login_Fail_AuthSystem_NotExistUser,
		Login_Fail_AuthSystem_WrongOwner,
		Login_Fail_AuthSystem_BlockedByAdmin,
		Login_Fail_AuthSystem_TempBlockedByLoginFail,
		Login_Fail_AuthSystem_WrongPwd,
		Login_Fail_AuthSystem_BlockedIP,
		Login_Fail_AuthSystem_Error,
		Login_Fail_InvalidPassport,
		Login_Success_Ageis0,
		Login_Success_TempUserChild,
		Login_Success_NoRealNameAgeOver19,
		Login_Success_TempPassword,
		Login_Fail_AuthSystem_BlockByEvent,
		Login_Fail_StolenNexonID,
		Login_Fail_AuthSystem_StealID,
		Login_Fail_AuthSystem_DormantID,
		UserIdentityBlock_NotExistIdentitySN = 9000,
		UserIdentityBlock_IsAlreadyBlock,
		UserIdentityBlock_IsBlockedIdentity,
		SMSReject_IsAlreadyExist = 9020,
		EmailReject_IsExistEmail,
		SMSReject_InputRestrictMobilePhoneNum,
		MypageEntrance_OverMaxFailCount = 9030,
		PwdHintChange_OverMaxFailCount = 9040,
		BlockIP_DuplicateIP = 9100,
		NexonNameModify_InvalidIndexSN = 9120,
		UserCashBlock_IsCashBlockUser = 9200,
		UserCashBlock_IsCharacterBlockUser,
		UserIpinChange_IsExistChannelingUser = 9210,
		UserIpinChange_IsOverMaxCount,
		UserIpinChange_ErrorReturnOnSoapCall,
		UserChanneling_IsAlreadyAllowGame = 9300,
		UserChanneling_InvalidGameCode,
		UserChanneling_InvalidChannelingCode,
		AuthCommon_EmptyInputData = 10100,
		AuthCommon_InvalidInputData,
		AuthCommon_NoMatchAuthCode,
		AuthCommon_InvalidAuthSN,
		OwnerCfm_DBError = 30001,
		OwnerCfm_InvalidInputData,
		OwnerCfm_GeneralError = 30101,
		OwnerCfm_InvalidMobileError,
		OwnerCfm_InvalidPersonalError,
		OwnerCfm_DecryptFail = 30201,
		OwnerCfm_ModuleCallError = 30901,
		OwnerCfm_UnKnownError
	}
}
