using System;
using System.Collections.Generic;
using Nexon.Com.DAO;

namespace Nexon.Com.UserWrapper
{
	internal class UserBasicGetListSoapResult : SoapResultBase
	{
		public List<UserBasicInfo> UserBasicList { get; internal set; }

		public int TotalRowCount { get; internal set; }

		public bool AdminUser { get; internal set; }

		public UserBasicGetListSoapResult()
		{
			this.UserBasicList = new List<UserBasicInfo>();
		}

		public void AddUserBasic(int? nexonSN, string nexonID, DateTime? createDate, DateTime? lastModifyDate, string nexonName, string name, string ssn, byte? sexCode, byte? age, bool? isTempBlockByLoginFail, bool? isTempBlockByWarning, bool? isTempUserChild, bool? isTempUserForeigner, bool? isTempUserCash, bool? isTempUserRealName, bool? isMainID, bool? isRealNameCfm, bool? isParentAuth, bool? isOwnerCfm, bool? isNotOwnerCfm, bool? isBlockByAdmin, bool? isTempPassword, bool? isModifyInfo_1, bool? isForeignerCfm, bool? isAlertState, bool? isCashParentAuth, bool? isCashParentReject, bool? isModifiedName, bool? isModifiedSsn, bool? isBackOfficeUser, bool? isSmsReceiveAgree, bool? isMobilePhoneAuth, bool? isRemovedByAdmin, bool? isForeigner, OpenConfigureCode? openConfigureName, OpenConfigureCode? openConfigureSex, OpenConfigureCode? openConfigureAge, OpenConfigureCode? openConfigureBirth, OpenConfigureCode? openConfigureSchool, OpenConfigureCode? openConfigureArea, OpenConfigureCode? openConfigurePhone, OpenConfigureCode? openConfigureMobilePhone, OpenConfigureCode? openConfigureEmail, byte? userCode, bool? isBlockCashRefillByAdmin, string email, string realBirth, byte? realBirthCode, DateTime? lastLoginTime, DateTime? prevLastLoginTime, byte? loginFailCount, DateTime? lastLoginFailTime, DateTime? lastPasswordChanged, byte? totalWarningPoint, DateTime? lastWarningTime, DateTime? blockEndDateByWarning, DateTime? maxEndWarning)
		{
			this.AddUserBasic(nexonSN, nexonID, createDate, lastModifyDate, nexonName, name, ssn, sexCode, age, isTempBlockByLoginFail, isTempBlockByWarning, isTempUserChild, isTempUserForeigner, isTempUserCash, isTempUserRealName, isMainID, isRealNameCfm, isParentAuth, isOwnerCfm, isNotOwnerCfm, isBlockByAdmin, isTempPassword, isModifyInfo_1, isForeignerCfm, isAlertState, isCashParentAuth, isCashParentReject, isModifiedName, isModifiedSsn, isBackOfficeUser, isSmsReceiveAgree, isMobilePhoneAuth, isRemovedByAdmin, isForeigner, openConfigureName, openConfigureSex, openConfigureAge, openConfigureBirth, openConfigureSchool, openConfigureArea, openConfigurePhone, openConfigureMobilePhone, openConfigureEmail, userCode, isBlockCashRefillByAdmin, email, realBirth, realBirthCode, lastLoginTime, prevLastLoginTime, loginFailCount, lastLoginFailTime, lastPasswordChanged, totalWarningPoint, lastWarningTime, blockEndDateByWarning, maxEndWarning, null, null, null, null, null);
		}

		public void AddUserBasic(int? nexonSN, string nexonID, DateTime? createDate, DateTime? lastModifyDate, string nexonName, string name, string ssn, byte? sexCode, byte? age, bool? isTempBlockByLoginFail, bool? isTempBlockByWarning, bool? isTempUserChild, bool? isTempUserForeigner, bool? isTempUserCash, bool? isTempUserRealName, bool? isMainID, bool? isRealNameCfm, bool? isParentAuth, bool? isOwnerCfm, bool? isNotOwnerCfm, bool? isBlockByAdmin, bool? isTempPassword, bool? isModifyInfo_1, bool? isForeignerCfm, bool? isAlertState, bool? isCashParentAuth, bool? isCashParentReject, bool? isModifiedName, bool? isModifiedSsn, bool? isBackOfficeUser, bool? isSmsReceiveAgree, bool? isMobilePhoneAuth, bool? isRemovedByAdmin, bool? isForeigner, OpenConfigureCode? openConfigureName, OpenConfigureCode? openConfigureSex, OpenConfigureCode? openConfigureAge, OpenConfigureCode? openConfigureBirth, OpenConfigureCode? openConfigureSchool, OpenConfigureCode? openConfigureArea, OpenConfigureCode? openConfigurePhone, OpenConfigureCode? openConfigureMobilePhone, OpenConfigureCode? openConfigureEmail, byte? userCode, bool? isBlockCashRefillByAdmin, string email, string realBirth, byte? realBirthCode, DateTime? lastLoginTime, DateTime? prevLastLoginTime, byte? loginFailCount, DateTime? lastLoginFailTime, DateTime? lastPasswordChanged, byte? totalWarningPoint, DateTime? lastWarningTime, DateTime? blockEndDateByWarning, DateTime? maxEndWarning, bool? isIpinUser)
		{
			this.AddUserBasic(nexonSN, nexonID, createDate, lastModifyDate, nexonName, name, ssn, sexCode, age, isTempBlockByLoginFail, isTempBlockByWarning, isTempUserChild, isTempUserForeigner, isTempUserCash, isTempUserRealName, isMainID, isRealNameCfm, isParentAuth, isOwnerCfm, isNotOwnerCfm, isBlockByAdmin, isTempPassword, isModifyInfo_1, isForeignerCfm, isAlertState, isCashParentAuth, isCashParentReject, isModifiedName, isModifiedSsn, isBackOfficeUser, isSmsReceiveAgree, isMobilePhoneAuth, isRemovedByAdmin, isForeigner, openConfigureName, openConfigureSex, openConfigureAge, openConfigureBirth, openConfigureSchool, openConfigureArea, openConfigurePhone, openConfigureMobilePhone, openConfigureEmail, userCode, isBlockCashRefillByAdmin, email, realBirth, realBirthCode, lastLoginTime, prevLastLoginTime, loginFailCount, lastLoginFailTime, lastPasswordChanged, totalWarningPoint, lastWarningTime, blockEndDateByWarning, maxEndWarning, isIpinUser, null, null, null, null);
		}

		public void AddUserBasic(int? nexonSN, string nexonID, DateTime? createDate, DateTime? lastModifyDate, string nexonName, string name, string ssn, byte? sexCode, byte? age, bool? isTempBlockByLoginFail, bool? isTempBlockByWarning, bool? isTempUserChild, bool? isTempUserForeigner, bool? isTempUserCash, bool? isTempUserRealName, bool? isMainID, bool? isRealNameCfm, bool? isParentAuth, bool? isOwnerCfm, bool? isNotOwnerCfm, bool? isBlockByAdmin, bool? isTempPassword, bool? isModifyInfo_1, bool? isForeignerCfm, bool? isAlertState, bool? isCashParentAuth, bool? isCashParentReject, bool? isModifiedName, bool? isModifiedSsn, bool? isBackOfficeUser, bool? isSmsReceiveAgree, bool? isMobilePhoneAuth, bool? isRemovedByAdmin, bool? isForeigner, OpenConfigureCode? openConfigureName, OpenConfigureCode? openConfigureSex, OpenConfigureCode? openConfigureAge, OpenConfigureCode? openConfigureBirth, OpenConfigureCode? openConfigureSchool, OpenConfigureCode? openConfigureArea, OpenConfigureCode? openConfigurePhone, OpenConfigureCode? openConfigureMobilePhone, OpenConfigureCode? openConfigureEmail, byte? userCode, bool? isBlockCashRefillByAdmin, string email, string realBirth, byte? realBirthCode, DateTime? lastLoginTime, DateTime? prevLastLoginTime, byte? loginFailCount, DateTime? lastLoginFailTime, DateTime? lastPasswordChanged, byte? totalWarningPoint, DateTime? lastWarningTime, DateTime? blockEndDateByWarning, DateTime? maxEndWarning, bool isHasSsn)
		{
			this.AddUserBasic(nexonSN, nexonID, createDate, lastModifyDate, nexonName, name, ssn, sexCode, age, isTempBlockByLoginFail, isTempBlockByWarning, isTempUserChild, isTempUserForeigner, isTempUserCash, isTempUserRealName, isMainID, isRealNameCfm, isParentAuth, isOwnerCfm, isNotOwnerCfm, isBlockByAdmin, isTempPassword, isModifyInfo_1, isForeignerCfm, isAlertState, isCashParentAuth, isCashParentReject, isModifiedName, isModifiedSsn, isBackOfficeUser, isSmsReceiveAgree, isMobilePhoneAuth, isRemovedByAdmin, isForeigner, openConfigureName, openConfigureSex, openConfigureAge, openConfigureBirth, openConfigureSchool, openConfigureArea, openConfigurePhone, openConfigureMobilePhone, openConfigureEmail, userCode, isBlockCashRefillByAdmin, email, realBirth, realBirthCode, lastLoginTime, prevLastLoginTime, loginFailCount, lastLoginFailTime, lastPasswordChanged, totalWarningPoint, lastWarningTime, blockEndDateByWarning, maxEndWarning, null, new bool?(isHasSsn), null, null, null);
		}

		public void AddUserBasic(int? nexonSN, string nexonID, DateTime? createDate, DateTime? lastModifyDate, string nexonName, string name, string ssn, byte? sexCode, byte? age, bool? isTempBlockByLoginFail, bool? isTempBlockByWarning, bool? isTempUserChild, bool? isTempUserForeigner, bool? isTempUserCash, bool? isTempUserRealName, bool? isMainID, bool? isRealNameCfm, bool? isParentAuth, bool? isOwnerCfm, bool? isNotOwnerCfm, bool? isBlockByAdmin, bool? isTempPassword, bool? isModifyInfo_1, bool? isForeignerCfm, bool? isAlertState, bool? isCashParentAuth, bool? isCashParentReject, bool? isModifiedName, bool? isModifiedSsn, bool? isBackOfficeUser, bool? isSmsReceiveAgree, bool? isMobilePhoneAuth, bool? isRemovedByAdmin, bool? isForeigner, OpenConfigureCode? openConfigureName, OpenConfigureCode? openConfigureSex, OpenConfigureCode? openConfigureAge, OpenConfigureCode? openConfigureBirth, OpenConfigureCode? openConfigureSchool, OpenConfigureCode? openConfigureArea, OpenConfigureCode? openConfigurePhone, OpenConfigureCode? openConfigureMobilePhone, OpenConfigureCode? openConfigureEmail, byte? userCode, bool? isBlockCashRefillByAdmin, string email, string realBirth, byte? realBirthCode, DateTime? lastLoginTime, DateTime? prevLastLoginTime, byte? loginFailCount, DateTime? lastLoginFailTime, DateTime? lastPasswordChanged, byte? totalWarningPoint, DateTime? lastWarningTime, DateTime? blockEndDateByWarning, DateTime? maxEndWarning, bool? isHasSsn, bool? isExistUser, bool? isPwdHashMatch, bool? isBlockByEvent)
		{
			if (this.UserBasicList == null)
			{
				this.UserBasicList = new List<UserBasicInfo>();
			}
			this.UserBasicList.Add(new UserBasicInfo(nexonSN, nexonID, createDate, lastModifyDate, nexonName, name, ssn, sexCode, age, isTempBlockByLoginFail, isTempBlockByWarning, isTempUserChild, isTempUserForeigner, isTempUserCash, isTempUserRealName, isMainID, isRealNameCfm, isParentAuth, isOwnerCfm, isNotOwnerCfm, isBlockByAdmin, isTempPassword, isModifyInfo_1, isForeignerCfm, isAlertState, isCashParentAuth, isCashParentReject, isModifiedName, isModifiedSsn, isBackOfficeUser, isSmsReceiveAgree, isMobilePhoneAuth, isRemovedByAdmin, isForeigner, openConfigureName, openConfigureSex, openConfigureAge, openConfigureBirth, openConfigureSchool, openConfigureArea, openConfigurePhone, openConfigureMobilePhone, openConfigureEmail, userCode, isBlockCashRefillByAdmin, email, realBirth, realBirthCode, lastLoginTime, prevLastLoginTime, loginFailCount, lastLoginFailTime, lastPasswordChanged, totalWarningPoint, lastWarningTime, blockEndDateByWarning, maxEndWarning, null, isHasSsn, isExistUser, isPwdHashMatch, isBlockByEvent));
		}

		public void AddUserBasic(int? nexonSN, string nexonID, DateTime? createDate, DateTime? lastModifyDate, string nexonName, string name, string ssn, byte? sexCode, byte? age, bool? isTempBlockByLoginFail, bool? isTempBlockByWarning, bool? isTempUserChild, bool? isTempUserForeigner, bool? isTempUserCash, bool? isTempUserRealName, bool? isMainID, bool? isRealNameCfm, bool? isParentAuth, bool? isOwnerCfm, bool? isNotOwnerCfm, bool? isBlockByAdmin, bool? isTempPassword, bool? isModifyInfo_1, bool? isForeignerCfm, bool? isAlertState, bool? isCashParentAuth, bool? isCashParentReject, bool? isModifiedName, bool? isModifiedSsn, bool? isBackOfficeUser, bool? isSmsReceiveAgree, bool? isMobilePhoneAuth, bool? isRemovedByAdmin, bool? isForeigner, OpenConfigureCode? openConfigureName, OpenConfigureCode? openConfigureSex, OpenConfigureCode? openConfigureAge, OpenConfigureCode? openConfigureBirth, OpenConfigureCode? openConfigureSchool, OpenConfigureCode? openConfigureArea, OpenConfigureCode? openConfigurePhone, OpenConfigureCode? openConfigureMobilePhone, OpenConfigureCode? openConfigureEmail, byte? userCode, bool? isBlockCashRefillByAdmin, string email, string realBirth, byte? realBirthCode, DateTime? lastLoginTime, DateTime? prevLastLoginTime, byte? loginFailCount, DateTime? lastLoginFailTime, DateTime? lastPasswordChanged, byte? totalWarningPoint, DateTime? lastWarningTime, DateTime? blockEndDateByWarning, DateTime? maxEndWarning, bool? isIpinUser, bool? isHasSsn, bool? isExistUser, bool? isPwdHashMatch, bool? isBlockByEvent)
		{
			if (this.UserBasicList == null)
			{
				this.UserBasicList = new List<UserBasicInfo>();
			}
			this.UserBasicList.Add(new UserBasicInfo(nexonSN, nexonID, createDate, lastModifyDate, nexonName, name, ssn, sexCode, age, isTempBlockByLoginFail, isTempBlockByWarning, isTempUserChild, isTempUserForeigner, isTempUserCash, isTempUserRealName, isMainID, isRealNameCfm, isParentAuth, isOwnerCfm, isNotOwnerCfm, isBlockByAdmin, isTempPassword, isModifyInfo_1, isForeignerCfm, isAlertState, isCashParentAuth, isCashParentReject, isModifiedName, isModifiedSsn, isBackOfficeUser, isSmsReceiveAgree, isMobilePhoneAuth, isRemovedByAdmin, isForeigner, openConfigureName, openConfigureSex, openConfigureAge, openConfigureBirth, openConfigureSchool, openConfigureArea, openConfigurePhone, openConfigureMobilePhone, openConfigureEmail, userCode, isBlockCashRefillByAdmin, email, realBirth, realBirthCode, lastLoginTime, prevLastLoginTime, loginFailCount, lastLoginFailTime, lastPasswordChanged, totalWarningPoint, lastWarningTime, blockEndDateByWarning, maxEndWarning, isIpinUser, isHasSsn, isExistUser, isPwdHashMatch, isBlockByEvent));
		}
	}
}
