//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Nexon.Com.UserWrapper.Properties {
    
    
    [CompilerGenerated]
	[GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.user.nexon.com/soap/securelogin.asmx")]
        public string Nexon_Com_UserWrapper_UserAPI_SecureLogin_securelogin {
            get {
                return ((string)(this["Nexon_Com_UserWrapper_UserAPI_SecureLogin_securelogin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.user.nexon.com/soap/qplayweb.asmx")]
        public string Nexon_Com_UserWrapper_UserAPI_QplayWeb_qplayweb {
            get {
                return ((string)(this["Nexon_Com_UserWrapper_UserAPI_QplayWeb_qplayweb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.user.nexon.com/soap/freecash.asmx")]
        public string Nexon_Com_UserWrapper_UserAPI_FreeCash_freecash {
            get {
                return ((string)(this["Nexon_Com_UserWrapper_UserAPI_FreeCash_freecash"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.user.nexon.com/soap/guestuser.asmx")]
        public string Nexon_Com_UserWrapper_UserAPI_GuestUser_guestuser {
            get {
                return ((string)(this["Nexon_Com_UserWrapper_UserAPI_GuestUser_guestuser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.user.nexon.com/soap/warning.asmx")]
        public string Nexon_Com_UserWrapper_UserAPI_Warning_warning {
            get {
                return ((string)(this["Nexon_Com_UserWrapper_UserAPI_Warning_warning"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.user.nexon.com/soap/p2.asmx")]
        public string Nexon_Com_UserWrapper_UserAPI_P2_p2 {
            get {
                return ((string)(this["Nexon_Com_UserWrapper_UserAPI_P2_p2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.user.nexon.com/soap/character.asmx")]
        public string Nexon_Com_UserWrapper_UserAPI_Character_character {
            get {
                return ((string)(this["Nexon_Com_UserWrapper_UserAPI_Character_character"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.user.nexon.com/soap/nexonstick.asmx")]
        public string Nexon_Com_UserWrapper_Nexon_Com_UserWrapper_UserAPI_NexonStick_nexonstick {
            get {
                return ((string)(this["Nexon_Com_UserWrapper_Nexon_Com_UserWrapper_UserAPI_NexonStick_nexonstick"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.user.nexon.com/soap/guildingame.asmx")]
        public string Nexon_Com_UserWrapper_Nexon_Com_UserWrapper_UserAPI_GuildInGame_guildingame {
            get {
                return ((string)(this["Nexon_Com_UserWrapper_Nexon_Com_UserWrapper_UserAPI_GuildInGame_guildingame"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.user.nexon.com/soap/seoul2012web.asmx")]
        public string Nexon_Com_UserWrapper_Nexon_Com_UserWrapper_UserAPI_SEOUL2012Web_seoul2012web {
            get {
                return ((string)(this["Nexon_Com_UserWrapper_Nexon_Com_UserWrapper_UserAPI_SEOUL2012Web_seoul2012web"]));
            }
        }
    }
}
